import {
  Compass,
  Mountain,
  Palmtree,
  House,
  Trees,
  Waves,
  Building2,
  Droplets,
  Home,
  Flower2,
  Wifi,
  Utensils,
  Car,
  Wind,
  Laptop,
  Fence,
} from "lucide-react";

export const categoryIcons = [
  Compass,
  Mountain,
  Palmtree,
  House,
  Trees,
  Waves,
  Building2,
  Droplets,
  Home,
  Flower2,
];
export const amenityIcons: Record<string, typeof Wifi> = {
  Wifi: Wifi,
  Kitchen: Utensils,
  "Free parking": Car,
  "Air conditioning": Wind,
  Pool: Waves,
  "Mountain view": Mountain,
  "Beach access": Palmtree,
  Washer: Droplets,
  Workspace: Laptop,
  Garden: Fence,
  "Lake view": Waves,
  "Hot tub": Droplets,
};
